### ISSUE TITLE
Hey this is impressive, I think you’re ahead of Alix haha :) 

### ISSUE THREAD

**Issue by colbyn** [payton-burr/Project3#7]
If you have any questions I’m happy to help.

**Comment by payton-burr** [comment]
Thanks! I took a break from this project because the web token was being such a pain. I'll go back and take another look and let you know if the issue persists.

**Comment by colbyn** [comment]
Yeah, doing lots of these projects is ultimately how I got comfortable with programming. You can reach me VIA Email if you want (`hello@colbyn.com`). I suppose I’ll just close this.
